# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/final_project/final_project/final_project.srcs/sources_1/ip/instruction_BRAM/instruction_BRAM.xci
# IP: The module: 'instruction_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/15spring/engs128/workspace/Brett_and_Matt/final_project/final_project/final_project.srcs/sources_1/ip/instruction_BRAM/instruction_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_BRAM'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: P:/15spring/engs128/workspace/Brett_and_Matt/final_project/final_project/final_project.srcs/sources_1/ip/instruction_BRAM/instruction_BRAM.xci
# IP: The module: 'instruction_BRAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/15spring/engs128/workspace/Brett_and_Matt/final_project/final_project/final_project.srcs/sources_1/ip/instruction_BRAM/instruction_BRAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'instruction_BRAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
